# Configuration File for Better Code Hub
# Reference - https://bettercodehub.com/docs/configuration-manual

---
# A depth of 2 examines components in the app folder individually.
# The resulting components are db, tweeter, and web.
# A depth of 1 examines the app folder as a single component.
component_depth: 2
# default_excludes: true
exclude:
  - /app/__dev__/.*
  - /_dockerfiles/web/__dev__/.*
languages:
  - python
