# Configuration File for Better Code Hub
# Reference - https://bettercodehub.com/docs/configuration-manual

---
component_depth: 1
# default_excludes: true
exclude:
  - /workspaces/ww-tweeter/app/__dev__/.*
  - /workspaces/ww-tweeter/_dockerfiles/web/__dev__/.*
  - \./app/__dev__/.*
  - \./_dockerfiles/web/__dev__/.*
languages:
  - python
