---
version: "3.9"

services:
  db:
    build:
      context: ./_dockerfiles/db
    env_file: ./_dockerfiles/db/.env
    image: db:14.1-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data

volumes:
  postgres: {}
