---
version: "3.9"

services:
  # PgAdmin
  db_admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./_dockerfiles/db_admin/.env
    networks:
      ww-tweeter:
        aliases:
          - db_admin
    ports:
      - 8080:80/tcp
    volumes:
      - ./_dockerfiles/db_admin/pg_admin:/var/lib/pgadmin
      - ./_dockerfiles/db_admin/pg_admin:/pgadmin4/servers.json

  # PostgreSQL
  ## Initialize DB after first run with the following commands via docker exec:
  ### psql
  ### create database ww_tweeter
  ### create database ww_tweeter_test
  db:
    build:
      context: ./_dockerfiles/db
    depends_on:
      - db_admin
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - ./_dockerfiles/db/.env
    networks:
      ww-tweeter:
        aliases:
          - db
    ports:
      - 5432:5432/tcp
    volumes:
      # - ./_dockerfiles/db/db_init:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data

  # Python application
  app:
    build:
      context: ./
    depends_on:
      - db_admin
      - db
    env_file:
      - ./app/.env
    networks:
      ww-tweeter:
        aliases:
          - app
          - web
    ports:
      - 8081:8080/tcp
    volumes:
      - ./app:/workspaces/ww-tweeter/app
      - ./tests:/workspaces/ww-tweeter/tests
      - ./pytest.ini:/workspaces/ww-tweeter/pytest.ini

volumes:
  db:

networks:
  ww-tweeter:
